sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 123321
    database: 10
  alioss:
    access-key-id: LTAI5tGdiZWoM4xPAnwwweCd
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-sw-itcast
    access-key-secret: whV0nEad897iVxgq2gQWurf5pXEWbU
  wechat:
    appid: wxb3d88cb4484293ce
    secret: 33b5845631f9308879771501322f47fe